
# Automatically generated by /Users/csuftitan/Git/cpsc120A/23FA/cpsc-120-solution-lab-09/.action/ccsrcutilities.py on 2023-10-30 21:21:31

TOPTARGETS = all clean spotless format lint header test unittest

SUBDIRS = $(wildcard part-?/.)

default all: all

$(TOPTARGETS): $(SUBDIRS)

$(SUBDIRS):
	$(MAKE) -f Makefile -C $@ $(MAKECMDGOALS)

.PHONY: $(TOPTARGETS) $(SUBDIRS)

